name: CreativeItemFilter
main: org.hurricanegames.creativeitemfilter.CreativeItemFilter
api-version: '1.21.1'
version: '@project.version@'
authors:
  - Jim (AnEnragedPigeon)
  - _Shevchik_

permissions:
  creativeitemfilter.reload:
    default: op
    description: Allows reloading the configuration
