[versions]
messagesHelperVersion = "1.1-SNAPSHOT"
pluginYmlPaperVersion = "0.9.0"
paperApiVersion = "26.1.2.build.+"

[libraries]
messagesHelper = { group = "uk.co.notnull", name= "MessagesHelper-paper", version.ref = "messagesHelperVersion" }
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApiVersion" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaperVersion" }